version: '3'

networks:
  prodnetwork:
    driver: bridge

volumes:
  nexus-data:
  tomcat:
      external: false
services:
  nexus:
    build: ./nexus
    restart: always
    ports:
      - "18081:8081"
    networks:
      - prodnetwork
    volumes:
      - nexus-data:/nexus-data
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    networks:
      - prodnetwork
    volumes:   
      - /var/run/docker.sock:/var/run/docker.sock
      - tomcat:/usr/share/jenkins/ref/tomcat
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
  tomcat:
        build: ./tomcat
        restart: always       
        ports:
            - "18888:8080"
        networks:
            - prodnetwork
        volumes:
            - tomcat:/usr/local/tomcat/webapps/
  sonardb:
    networks:
      - prodnetwork
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
  sonar:
    image: sonarqube
    restart: always
    ports:
     - "19000:9000"
     - "19092:9092"
    networks:
      - prodnetwork
    depends_on:
      - sonardb
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
